language: go

go:
  - 1.8.3
install:
   - curl https://glide.sh/get | sh
   - glide install
script: make build

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - npm install -g codecov
  - codecov
