sudo: required

addons:
  apt:
    packages:
      - docker-ce

script:
  - make ckeckstyle test build-image VERSION=`cat VERSION`-$TRAVIS_BUILD_NUMBER

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - npm install -g codecov
  - codecov
